import Head from 'next/head';
import Link from 'next/link';
import { getPortfolioItem, getPortfolioSlugs } from '../../lib/data';
import { useRouter } from 'next/router';

export const getStaticPaths = async () => {
  const slugsRes = await getPortfolioSlugs();
  const slugs = slugsRes.portfolios;
  const paths = slugs.map((slug) => {
    return {
      params: {
        slug: slug.slug,
      },
    };
  });

  return {
    paths,
    fallback: false,
  };
};

export const getStaticProps = async ({ params }) => {
  console.log(params);
  const portfolioItem = await getPortfolioItem(params.slug);
  // console.log(portfolioItem);
  return {
    props: {
      portfolioItem: portfolioItem,
    },
  };
};

const PortfolioPage = ({ portfolioItem }) => {
  const router = useRouter();
  console.log(portfolioItem);

  if (router.isFallback) {
    return <div>Loading...</div>;
  }

  return (
    <>
      <Head>
        <title>Awesome Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div></div>
    </>
  );
};

export default PortfolioPage;
