import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import { getPortfolioItem, getPortfolioSlugs } from '../../lib/data';
import { serialize } from 'next-mdx-remote/serialize';
import { MDXRemote } from 'next-mdx-remote';
import he from 'he';

export const getStaticPaths = async () => {
  const slugsRes = await getPortfolioSlugs();
  const slugs = slugsRes.portfolios;
  const paths = slugs.map((slug) => {
    return {
      params: {
        slug: slug.slug,
      },
    };
  });

  return {
    paths,
    fallback: false,
  };
};

export const getStaticProps = async ({ params }) => {
  const portfolioItem = await getPortfolioItem(params.slug);
  return {
    props: {
      portfolio: portfolioItem.portfolio,
      content: await serialize(he.decode(portfolioItem.portfolio.content)),
    },
  };
};

const PortfolioPage = ({ portfolio, content }) => {
  return (
    <>
      <Head>
        <title>Awesome Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container max-w-3xl mx-auto px-4 py-5 lg:py-10">
        <h1 className="font-bold text-3xl lg:text-6xl">{portfolio.title}</h1>
        <p className="mt-3">{new Date(portfolio.date).toDateString()}</p>

        <div className="mt-3 space-x-4 text-center">
          {portfolio.tags.map((tag) => {
            return (
              <span key={tag} className="btn btn-primary btn-sm">
                {tag}
              </span>
            );
          })}
        </div>
        <div className="mt-5">
          <Image
            src={portfolio.coverImage.url}
            width={portfolio.coverImage.width}
            height={portfolio.coverImage.height}
            alt={portfolio.title}
          />
        </div>
        <div className="mt-5 lg:mt-10 prose max-w-none prose-invert">
          <MDXRemote {...content} />
        </div>
      </main>
    </>
  );
};

export default PortfolioPage;
