import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import { getPortfolioItem, getPortfolioSlugs } from '../../lib/data';
import { serialize } from 'next-mdx-remote/serialize';
import { MDXRemote } from 'next-mdx-remote';
import he from 'he';

export const getStaticPaths = async () => {
  const slugsRes = await getPortfolioSlugs();
  const slugs = slugsRes.portfolios;
  const paths = slugs.map((slug) => {
    return {
      params: {
        slug: slug.slug,
      },
    };
  });

  return {
    paths,
    fallback: false,
  };
};

export const getStaticProps = async ({ params }) => {
  const portfolioItem = await getPortfolioItem(params.slug);
  return {
    props: {
      portfolio: portfolioItem.portfolio,
      content: await serialize(he.decode(portfolioItem.portfolio.content)),
    },
  };
};

const PortfolioPage = ({ portfolio, content }) => {
  return (
    <>
      <Head>
        <title>Awesome Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>{portfolio.title}</h1>
        <p>{new Date(portfolio.date).toDateString()}</p>
        <p>{portfolio.description}</p>
        <div>
          {portfolio.tags.map((tag) => {
            return <span key={tag}>{tag}</span>;
          })}
        </div>
        <Image
          src={portfolio.coverImage.url}
          width={portfolio.coverImage.width}
          height={portfolio.coverImage.height}
          alt={portfolio.title}
        />
        <MDXRemote {...content} />
      </main>
    </>
  );
};

export default PortfolioPage;
