import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import { getPostItem, getPostSlugs } from '../../lib/data';
import { serialize } from 'next-mdx-remote/serialize';
import { MDXRemote } from 'next-mdx-remote';
import he from 'he';

export const getStaticPaths = async () => {
  const slugsRes = await getPostSlugs();
  const slugs = slugsRes.posts;
  const paths = slugs.map((slug) => {
    return {
      params: {
        slug: slug.slug,
      },
    };
  });

  return {
    paths,
    fallback: false,
  };
};

export const getStaticProps = async ({ params }) => {
  const postItem = await getPostItem(params.slug);
  return {
    props: {
      post: postItem.post,
      content: await serialize(he.decode(postItem.post.content)),
    },
  };
};

const BlogPage = ({ post, content }) => {
  return (
    <>
      <Head>
        <title>Awesome Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container max-w-3xl mx-auto px-4 py-5 lg:py-10">
        <h1 className="font-bold text-3xl lg:text-6xl">{post.title}</h1>
        <div className="flex items-center justify-between">
          <p className="">{new Date(post.date).toDateString()}</p>
          <div className="flex justify-center items-center gap-x-5">
            <p className="">{post.author.name}</p>
            <Image
              src={post.author.image.url}
              width={64}
              height={64}
              alt={post.title}
              objectFit="cover"
              className="w-16 h-16 rounded-full "
            />
          </div>
        </div>
        <div className="mt-3 space-x-4 text-center">
          {post.tags.map((tag) => {
            return (
              <span className="btn btn-primary btn-sm" key={tag}>
                {tag}
              </span>
            );
          })}
        </div>
        <div className="mt-5 lg:mt-10 prose max-w-none prose-invert">
          <MDXRemote {...content} />
        </div>
      </main>
    </>
  );
};

export default BlogPage;
