import Head from 'next/head';
import { request, GraphQLClient, gql } from 'graphql-request';
import Link from 'next/link';
import { getPostsAndPortfolios } from '../lib/data';

export const getStaticProps = async () => {
  const data = await getPostsAndPortfolios();
  return {
    props: {
      data,
    },
  };
};

export default function Home({ data }) {
  // console.log(data);
  return (
    <div>
      <Head>
        <title>Awesome Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        {data?.portfolios.map((item) => {
          return (
            <div key={item.slug}>
              <Link href={`/portfolio/${item.slug}`}>
                <a>{item.title}</a>
              </Link>
            </div>
          );
        })}
      </div>

      <div className="mt-5">
        {data?.posts.map((post) => {
          return (
            <div key={post.slug}>
              <Link href={`/blog/${post.slug}`}>{post.title}</Link>
            </div>
          );
        })}
      </div>
      <h1>Awesome Portfolio</h1>
    </div>
  );
}
